updated Chart for single Neo4J instance; removed unnecessary artifacts;

diff --git a/templates/tests/test-script.yaml b/templates/tests/test-script.yaml
--- a/templates/tests/test-script.yaml
+++ b/templates/tests/test-script.yaml
@@ -14,7 +14,6 @@ data:
   run.sh: |-
     export PATH=/usr/bin:$PATH
     export host="$NAME-neo4j.$NAMESPACE.svc.cluster.local"
-    export replica_host="$NAME-readreplica-svc.$NAMESPACE.svc.cluster.local"
     echo "HOST $host"
     # This endpoint proves availability of the overall service
     export endpoint="http://$host:$PORT_HTTP"
@@ -23,8 +22,6 @@ data:
     export NEO4J_SECRETS_PASSWORD=$(cat /secret/neo4j-password)
     export auth="neo4j:${NEO4J_SECRETS_PASSWORD}"
     echo "AUTH $auth"
-    echo "CORES $CORES"
-    echo "RRs $READ_REPLICAS"
 
     # When test resources are deployed cluster hasn't had a chance to form yet.
     # This polls in a loop waiting for cluster to become available, and gives up/fails
@@ -49,10 +46,8 @@ data:
       sleep 5
     done
 
-    # Pass index ID to get hostname for that pod.
     function core_hostname {
-      # Example: a-neo4j-core-0.a-neo4j.default.svc.cluster.local
-      echo "$NAME-neo4j-core-$1.$NAME-neo4j.$NAMESPACE.svc.cluster.local"
+      echo "$NAME-neo4j-core-0.$NAME-neo4j.$NAMESPACE.svc.cluster.local"
     }
 
     test_index=0
@@ -121,56 +116,19 @@ data:
 
     echo "All pre-requisites met, beginning main testing"
 
-    echo "Basic topology upfront"
-    cypher "CALL dbms.cluster.overview();"
-
     runtest "Bolt is available, port $PORT_BOLT"               "RETURN 'yes';"
     runtest "Basic read queries"                               "MATCH (n) RETURN COUNT(n);"
-    runtest "Database is in clustered mode"                    "CALL dbms.cluster.overview();" 
-    runtest "Cluster accepts writes"                           'CREATE (t:TestNode) RETURN count(t);'
+    runtest "Database accepts writes"                          'CREATE (t:TestNode) RETURN count(t);'
 
-    # Data from server on cluster topology.
-    topology=$(cypher "CALL dbms.cluster.overview();")
-    echo "TOPOLOGY $topology"
+    # Database is up and configured.
+    core_host=$(core_hostname)
+    core_endpoint="bolt://$core_host:$PORT_BOLT"
 
-    # LEADERS
-    leaders=$(echo $topology | grep 'system: "LEADER"' | wc -l)
-    test="Cluster has 1 system leader"
-    if [ $leaders -eq 1 ] ; then
-      succeed "$test"
-    else
-      fail "$test" "$leaders leaders"
-    fi
+    test="Core host -- $core_endpoint is available"
+    runtest "$test" "MATCH (n) RETURN COUNT(n);" "$core_endpoint"
 
-    # FOLLOWERS
-    followers=$(echo $topology | grep -o 'system: "FOLLOWER"' | wc -l)
-    test="Cluster has 1-CORES followers"
-    if [ $followers -eq $((CORES-1)) ] ; then
-      succeed "$test"
-    else
-      fail "$test" "$followers followers"
-    fi
-
-    # REPLICAS
-    read_replicas=$(echo $topology | grep -o 'system: "READ_REPLICA"' | wc -l)
-    test="Cluster has $READ_REPLICAS read replicas"
-    if [ $read_replicas -eq $READ_REPLICAS ] ; then
-      succeed "$test"
-    else
-      fail "$test" "$read_replicas replicas"
-    fi
-
-    # Each core is individually up and configured.
-    for id in $(seq 0 $((CORES - 1))); do
-      core_host=$(core_hostname $id)
-      core_endpoint="bolt://$core_host:$PORT_BOLT"
-
-      test="Core host $id of $CORES -- $core_endpoint is available"
-      runtest "$test" "MATCH (n) RETURN COUNT(n);" "$core_endpoint"
-
-      test="Core host $id of $CORES -- $core_endpoint has APOC installed correctly"
-      runtest "$test" "RETURN apoc.version();" "$core_endpoint"
-    done
+    test="Core host -- $core_endpoint has APOC installed correctly"
+    runtest "$test" "RETURN apoc.version();" "$core_endpoint"
 
     # Test for data replication.
     runtest "Sample canary write" 'CREATE (c:Canary) RETURN count(c);'
@@ -178,27 +136,25 @@ data:
     sleep 5
 
     # Check each core, count the canary writes. They should all agree.
-    for id in $(seq 0 $((CORES - 1))); do
-      core_host=$(core_hostname $id)
-      # Use bolt driver, not routing driver, to ensure that test verifies data
-      # exists on this host.
-      core_endpoint="bolt://$core_host:$PORT_BOLT"
-      test="Core host $id has the canary write"
-      result=$(cypher "MATCH (c:Canary) WITH count(c) as x where x = 1 RETURN x;" "$core_endpoint")
-      exit_code=$?
-      if [ $exit_code -eq 0 ] ; then
-        # Check that the data is there.
-        found_results=$(echo "$result" | grep -o 1 | wc -l)
+    core_host=$(core_hostname)
+    # Use bolt driver, not routing driver, to ensure that test verifies data
+    # exists on this host.
+    core_endpoint="bolt://$core_host:$PORT_BOLT"
+    test="Core host has the canary write"
+    result=$(cypher "MATCH (c:Canary) WITH count(c) as x where x = 1 RETURN x;" "$core_endpoint")
+    exit_code=$?
+    if [ $exit_code -eq 0 ] ; then
+      # Check that the data is there.
+      found_results=$(echo "$result" | grep -o 1 | wc -l)
 
-        if [ $found_results -eq 1 ] ; then
-          succeed "$test"
-        else 
-          fail "$test" "Canary read did not return data -- $found_results found results from $result"
-        fi
-      else
-        fail "$test" "Canary read failed to execute -- exit code $exit_code / RESULT -- $result"
+      if [ $found_results -eq 1 ] ; then
+        succeed "$test"
+      else 
+        fail "$test" "Canary read did not return data -- $found_results found results from $result"
       fi
-    done
+    else
+      fail "$test" "Canary read failed to execute -- exit code $exit_code / RESULT -- $result"
+    fi
 
     echo "All good; testing completed"
     exit 0
